name: GitHub Actions
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  Build_Docker_Image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
      - name: Go to App directory and build image
        run: cd TicketingApp && docker build . -t ticketing_app:$(date +%s)