name: Publish Docker Image
run-name: ${{ github.actor }} is publishing docker images
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  push_to_docker_hub:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      
      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: name/app

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:TicketingApp"
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}